name: Update index.html on subdirectory changes

on:
  push:
    paths:
      - 'BLELogger/**'
    paths-ignore:
      - 'index.html'

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get most recent changed file in subdirectory
        id: changed-files
        run: |
          # Get all changed files in the "subdirectory" between the previous and current commits.
          CHANGED_FILES=$(git diff --name-only "${{ github.event.before }}" "${{ github.sha }}" | grep '^subdirectory/')
          # Select the last file from the list (assumed to be the most recent change)
          MOST_RECENT_FILE=$(echo "$CHANGED_FILES" | tail -n 1)
          echo "changed_file=$MOST_RECENT_FILE" >> $GITHUB_OUTPUT
          echo "CHANGED_FILE=$MOST_RECENT_FILE" >> $GITHUB_ENV

      - name: Update index.html with the most recent file name
        run: |
          # Write only the file name to index.html (no HTML wrapper)
          echo "$CHANGED_FILE" > index.html

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          # Commit only if there is a change to index.html.
          git commit -m "Update index.html with the most recent file name" || echo "No changes to commit"
          git push
